CREATE TABLE TB_CUSTOMER(
    ID UNIQUEIDENTIFIER DEFAULT NEWID() NOT NULL,
    FIRSTNAME VARCHAR(50),
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(100),
    PASSWORD VARCHAR(255)

)

ALTER TABLE TB_CUSTOMER ADD CONSTRAINT PK_TB_CUSTOMER PRIMARY KEY CLUSTERED(ID)